version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "ship-ctrl"
    assignees:
      - "ship-ctrl"
    labels:
      - "dependencies"
      - "gitsubmodule"
